name: BASE9

on:
 push:
  branches:
   - master
   - main

# if: ${{ false }}

jobs:

# base9 --------------------------------------------------------------
 base9:
  name: BASE9
  runs-on: ubuntu-20.04
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v3

   - name: Build BASE9
     run: |
      cd ~/
      wget https://www.jsoftware.com/download/j9.6/install/j9.6_linux64.tar.gz
      tar -xzf j9.6_linux64.tar.gz
      cd -
      echo "UserFolders_j_=: ~. UserFolders_j_,'Main';'`pwd`'" > bld.ijs
      echo "load 'project'" >> bld.ijs
      echo "load '~Main/save/build.ijs'" >> bld.ijs
      echo "exit 0" >> bld.ijs
      cat bld.ijs
      ~/j9.6/bin/jconsole bld.ijs || exit 1
      mkdir -p release/install/bin
      cp config/profile* release/install/bin/.
      cd release
      tar -czf ../base9.tar.gz install
      cd -
      cp config/version.txt .
      ls -l

   - name: Release
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: "base9.tar.gz,version.txt"
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true

# webhook --------------------------------------------------------------
 webhook:
  name: Run Webhook
# remove the following line to run
#  if: ${{ false }}
  runs-on: ubuntu-20.04
  needs: base9
  steps:
   - name: update server
     uses: distributhor/workflow-webhook@v2
     env:
      webhook_url: ${{ secrets.WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      data: '{ "id": "base9" }'
